# FileName:   Makefile
# Author:     Fasion Chan
# @contact:   fasionchan@gmail.com
# @version:   $Id$
#
# Description:
#
# Changelog:
#

all: \
	vector1 deque1 list1 list2 iterator set1 mmap1 map1 algo1 find1 \
	copy1 copy2 copy3 ioiter1 riter1 remove1 remove2 remove3 remove4 \
	foreach1 transform1 prime1 foreach2 add1 fo1 iterbug1
	echo

vector1: vector1.cpp
	g++ -o $@ $^

deque1: deque1.cpp
	g++ -o $@ $^

list1: list1.cpp
	g++ -o $@ $^

list2: list2.cpp
	g++ -o $@ $^

iterator: iterator.cpp
	g++ -o $@ $^

set1: set1.cpp
	g++ -o $@ $^

mmap1: mmap1.cpp
	g++ -o $@ $^

map1: map1.cpp
	g++ -o $@ $^

algo1: algo1.cpp
	g++ -o $@ $^

find1: find1.cpp
	g++ -o $@ $^

copy1: copy1.cpp
	g++ -o $@ $^

copy2: copy2.cpp
	g++ -o $@ $^

copy3: copy3.cpp
	g++ -o $@ $^

ioiter1: ioiter1.cpp
	g++ -o $@ $^

riter1: riter1.cpp
	g++ -o $@ $^

remove1: remove1.cpp
	g++ -o $@ $^

remove2: remove2.cpp
	g++ -o $@ $^

remove3: remove3.cpp
	g++ -o $@ $^

remove4: remove4.cpp
	g++ -o $@ $^

foreach1: foreach1.cpp
	g++ -o $@ $^

transform1: transform1.cpp
	g++ -o $@ $^

prime1: prime1.cpp
	g++ -o $@ $^

foreach2: foreach2.cpp
	g++ -o $@ $^

add1: add1.cpp
	g++ -o $@ $^

fo1: fo1.cpp
	g++ -o $@ $^

iterbug1: iterbug1.cpp
	g++ -o $@ $^

clean:
	rm -rf vector1 deque1 list1 list2 iterator set1 mmap1 map1 algo1 find1 \
			copy1 copy2 copy3 ioiter1 riter1 remove1 remove2 remove3 remove4 \
			foreach1 transform1 prime1 foreach2 add1 fo1 iterbug1
