# FileName:   Makefile
# Author:     Fasion Chan
# @contact:   fasionchan@gmail.com
# @version:   $Id$
#
# Description:
#
# Changelog:
#
#

all:
	g++ -o autoptr1 autoptr1.cpp
	g++ -o autoptr2 autoptr2.cpp
	g++ -o limit1 limit1.cpp
	g++ -o minmax1 minmax1.cpp


clean:
	rm -f autoptr1 autoptr2 limit1 minmax1
